version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/laravel-api-crud-template:1.0.2
    container_name: laravel-api-crud-template-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - /var/www/vendor
    depends_on:
      - db
      - smtp
      - soketi
      - redis

  nginx:
    image: nginx:alpine
    container_name: laravel-api-crud-template-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose-config/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mariadb:11.2.2
    container_name: laravel-api-crud-template-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker-compose-config/mariadb/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  smtp:
    image: jcalonso/mailhog:v1.0.1
    container_name: laravel-api-crud-template-smtp
    restart: unless-stopped
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - smtp-data:/home/mailhog

  soketi:
    image: quay.io/soketi/soketi:1.6-16-debian
    container_name: laravel-api-crud-template-soketi
    restart: unless-stopped
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_METRICS_SERVER_PORT: "9601"
    volumes:
      - './docker-compose-config/soketi/config.json:/opt/config.json'
    command: ["node", "/app/bin/server.js", "start", "--config=/opt/config.json"]

  redis:
    image: redis:7.2.4
    container_name: laravel-api-crud-template-redis
    restart: unless-stopped
    volumes:
      - ./docker-compose-config/redis/redis.conf:/etc/redis/redis.conf
      - redis-data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "/etc/redis/redis.conf"]

networks:
  laravel-api-crud-template:
    driver: bridge

volumes:
  db-data:
  smtp-data:
  redis-data: