version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/laravel-api-crud-template:1.0.0
    restart: unless-stopped
    networks:
      - laravel-api-crud-template
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - laravel-api-crud-template
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mariadb:11.2.2
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel-api-crud-template
    volumes:
      - ./docker-compose/mariadb/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

networks:
  laravel-api-crud-template:
    driver: bridge

volumes:
  db-data: