version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: javi98/laravel-api-crud-template:1.0.1
    container_name: laravel-api-crud-template-app
    restart: unless-stopped
    networks:
      - laravel-api-crud-template
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - smtp

  nginx:
    image: nginx:alpine
    container_name: laravel-api-crud-template-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - laravel-api-crud-template
    volumes:
      - ./:/var/www
      - ./docker-compose-config/nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mariadb:11.2.2
    container_name: laravel-api-crud-template-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - laravel-api-crud-template
    volumes:
      - ./docker-compose-config/mariadb/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  smtp:
    image: jcalonso/mailhog:v1.0.1
    container_name: laravel-api-crud-template-smtp
    restart: unless-stopped
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - smtp-data:/home/mailhog
    networks:
      - laravel-api-crud-template

networks:
  laravel-api-crud-template:
    driver: bridge

volumes:
  db-data:
  smtp-data: